export const events = [
  {
    title: "Next.js Conf 2025",
    slug: "nextjs-conf-2025",
    image: "/images/event1.png",
    location: "San Francisco, CA",
    date: "October 24, 2025",
    time: "9:00 AM PST",
  },
  {
    title: "React Summit US 2025",
    slug: "react-summit-us-2025",
    image: "/images/event2.png",
    location: "New York, NY",
    date: "November 18–21, 2025",
    time: "10:00 AM EST",
  },
  {
    title: "GitHub Universe 2025",
    slug: "github-universe-2025",
    image: "/images/event3.png",
    location: "San Francisco, CA",
    date: "October 28–29, 2025",
    time: "9:00 AM PST",
  },
  {
    title: "Node.js Collaborator Summit",
    slug: "nodejs-collaborator-summit-2025",
    image: "/images/event4.png",
    location: "Amsterdam, Netherlands",
    date: "November 4, 2025",
    time: "9:30 AM CET",
  },
  {
    title: "AWS re:Invent 2025",
    slug: "aws-reinvent-2025",
    image: "/images/event5.png",
    location: "Las Vegas, NV",
    date: "December 1–5, 2025",
    time: "8:00 AM PST",
  },
  {
    title: "Google Cloud Next 2026",
    slug: "google-cloud-next-2026",
    image: "/images/event6.png",
    location: "Las Vegas, NV",
    date: "April 9–11, 2026",
    time: "9:00 AM PDT",
  },
];
